
#Modify how certain items and mobs work
[Tools]
	#Enables or disabled technical levels of thermometers. Gives minecraft temperature values instead of adapted ones.
	technicalThermometer = false
	#The percent chance that the snowman zapper will stick a transponder on his target if one is available.
	#Range: 0 ~ 100
	transponderStick = 20
	#Plague variants of the Cold Snap Horde can infect attack entities with Immortuos Calyx if it is installed alongside this mod.
	plagueImmortuosCompat = true
	#Horde snowmen take double damage from fire.
	fireMeltsSnowBetter = true
	#How long in ticks (20 per second by default) it takes for a frosty cow to be ready to be "milked" for powdered snow again.
	frostyHarvestCooldown = 1800

#Modify how hordes operate. Spawn rates, life counters, etc.
["Horde Settings"]
	#How long in seconds players need to wait inbetween Snowglobe usage (Spawning a notable number of snowmen)
	#Range: 1 ~ 3600
	globalHordeCooldown = 60
	#How many horde members will a tier 1 horde attempt to spawn at once. Once this limit is reached, the horde will not spawn more members until the amount of members alive or in range fall below this number
	#Range: 5 ~ 50
	tier1SnowmanHordeSize = 5
	#Default amount of horde members needed to be killed in a tier 1 horde on easy difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier1EasyAliveCount = 20
	#Default amount of horde members needed to be killed in a tier 1 horde on normal difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier1NormalAliveCount = 30
	#Default amount of horde members needed to be killed in a tier 1 horde on hard difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier1HardAliveCount = 40
	#How many horde members will a tier 2 horde attempt to spawn at once. Once this limit is reached, the horde will not spawn more members until the amount of members alive or in range fall below this number
	#Range: 5 ~ 50
	tier2SnowmanHordeSize = 8
	#Default amount of horde members needed to be killed in a tier 2 horde on easy difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier2EasyAliveCount = 35
	#Default amount of horde members needed to be killed in a tier 2 horde on normal difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier2NormalAliveCount = 50
	#Default amount of horde members needed to be killed in a tier 2 horde on hard difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier2HardAliveCount = 65
	#How many horde members will a tier 3 horde attempt to spawn at once. Once this limit is reached, the horde will not spawn more members until the amount of members alive or in range fall below this number
	#Range: 5 ~ 50
	tier3SnowmanHordeSize = 10
	#Default amount of horde members needed to be killed in a tier 3 horde on easy difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier3EasyAliveCount = 50
	#Default amount of horde members needed to be killed in a tier 3 horde on normal difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier3NormalAliveCount = 65
	#Default amount of horde members needed to be killed in a tier 3 horde on hard difficulty before the horde deactivates with a player victory
	#Range: 1 ~ 20000
	tier3HardAliveCount = 80
	#How often more expensive update ticks occur. This allows new in range players to get the bossbar, and updates the horde with the position of their main target. Higher reduces frequency of these more expensive ticks, but lowers horde responsiveness.
	#Range: 20 ~ 3600
	hordeUpdateCooldown = 100

